version: "3.3"

services:
  ################### Backend #########################
  app:
    build:
      context: ./Backend/src/
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 4000:3000
    restart: always
    depends_on:
      - cache
    networks:
      - app_network
  cache:
    image: redis
    container_name: cache
    ports:
      - 6379:6379
    restart: always
    networks:
      - app_network
networks:
  app_network: {}